configs = dict(
    render_params=dict(render_size=(384, 512), aa_factor=2),
    lights=dict(PointLight=dict(type="PointLight",
                                color_scale_range=((1.0, 1.0), (0.1, 0.1), (0.1, 0.1)),
                                color_delta=(0, 0),
                                location_rage=((0, 0), (1, 1), (0, 0))),
                ),
    meshes=dict(Environment=dict(type="Environments", environments_dir="data/environments",
                                 item_list=["poly_haven_studio_4k.png"], sphere_radius=10000, translate_y=0),
                Victim=dict(type="Victims", dataset_dir="data/dataset", scale_range=(0.9, 0.9),
                            rotate_range=((0, 0), (0, 0), (0, 0)),
                            translate_range=((0, 0), (0, 0), (0, 0)),
                            target_objects=dict(teddy_bear=["teddy_bear_009"])),
                Carrier=dict(type="Carrier",
                                  mesh_type="MeshDisc",
                                  mesh_params=dict(disc_path="data/carriers/disc/carrier.obj",
                                                   disc_radius_range=(1, 1), rotate_range=(0, 0),
                                                   translate_range=((0.0, 0.0), (0.0, 0.0), (0.0, 0.0))),
                                  texture_type="TextureDisc",
                                  texture_params=dict(image_path="", down_up_sample_scale=1.0)),
                ),
    cameras=dict(type="Cameras", num_views=5, dist=[2.4], pitch_degree=[55], yaw_degree=[0, 72, 144, 216, 288],
                 at=[((0, 0, 0),)], roll_degree=[0]),
    view_params={
        "default": dict(light="PointLight", meshes_groups=["Environment", "Carrier", "Victim"], meshes_transforms=dict()),
        0: dict(meshes_transforms=dict()),
        1: dict(meshes_transforms=dict()),
        2: dict(meshes_transforms=dict()),
        3: dict(meshes_transforms=dict()),
        4: dict(meshes_transforms=dict()),},
)
